export const ActionCatalog = {
  AuthLoginRequested: 'auth/loginRequested',
  AuthSignupRequested: 'auth/signupRequested',
  AuthGoogleLoginRequested: 'auth/googleLoginRequested',
  AuthPasswordResetRequested: 'auth/passwordResetRequested',
  AuthLogoutRequested: 'auth/logoutRequested',
  AuthSetUser: 'auth/setUser',
  AuthSetUi: 'auth/setUi',
  EffectsFrameworkMenuHydrate: 'effects/frameworkMenu/hydrate',
  EffectsFrameworkMenuSave: 'effects/frameworkMenu/save',
  EffectsPresetsDelete: 'effects/presets/delete',
  EffectsPresetsHydrate: 'effects/presets/hydrate',
  EffectsPresetsRename: 'effects/presets/rename',
  EffectsPresetsSave: 'effects/presets/save',
  FrameworkMenuHydrate: 'frameworkMenu/hydrate',
  FrameworkMenuReorderItems: 'frameworkMenu/reorderItems',
  FrameworkMenuUpdateConfig: 'frameworkMenu/updateConfig',
  LayoutDragEnd: 'layout/dragEnd',
  LayoutDragStart: 'layout/dragStart',
  LayoutSetExpansion: 'layout/setExpansion',
  LayoutSetMainAreaCount: 'layout/setMainAreaCount',
  LayoutSetOverlayView: 'layout/setOverlayView',
  LayoutSetViewportWidthMode: 'layout/setViewportWidthMode',
  LayoutResetWorkspace: 'layout/resetWorkspace',
  LayoutToggleInDesign: 'layout/toggleInDesign',
  LogsAppend: 'logs/append',
  LogsClear: 'logs/clear',
  PanelsAssignView: 'panels/assignView',
  PanelsRemoveView: 'panels/removeView',
  PanelsSelectPanel: 'panels/selectPanel',
  PanelsSetMainViewOrder: 'panels/setMainViewOrder',
  PresetsDelete: 'presets/delete',
  PresetsHydrate: 'presets/hydrate',
  PresetsLoad: 'presets/load',
  PresetsRename: 'presets/rename',
  PresetsSave: 'presets/save',
  StateHydrate: 'state/hydrate',
  ViewUpdateLocalContext: 'view/updateLocalContext',
} as const;

export type ActionName = (typeof ActionCatalog)[keyof typeof ActionCatalog];
